"""Report renderers for GRIM: Markdown and JSON."""

from __future__ import annotations

import json
from typing import Any, Iterable

from .findings import Finding, summarize

SEV_LABEL = {
    "critical": "CRITICAL",
    "high": "HIGH",
    "medium": "MEDIUM",
    "low": "LOW",
    "info": "INFO",
}


def render_json(findings: Iterable[Finding], meta: dict[str, Any] | None = None) -> str:
    payload = {
        "grim": {"version": _version(), "meta": meta or {}},
        "summary": summarize(findings),
        "findings": [f.to_dict() for f in findings],
    }
    return json.dumps(payload, indent=2, default=str)


def render_markdown(findings: Iterable[Finding], meta: dict[str, Any] | None = None) -> str:
    findings = list(findings)
    s = summarize(findings)
    lines: list[str] = []
    lines.append("# GRIM Security Report")
    lines.append("")
    if meta:
        for k, v in meta.items():
            lines.append(f"- **{k}:** {v}")
    lines.append(f"- **Target:** {meta.get('target', '-') if meta else '-'}")
    lines.append(f"- **Total findings:** {s['total']}")
    by = s["by_severity"]
    lines.append(
        "- **Severity:** "
        + " | ".join(f"{SEV_LABEL[k]}: {by.get(k, 0)}" for k in ["critical", "high", "medium", "low", "info"])
    )
    lines.append("")

    if not findings:
        lines.append("No findings. Clean.")
        return "\n".join(lines)

    for f in findings:
        loc = f.location.get("file") or f.location.get("url") or ""
        line = f", line {f.location['line']}" if f.location.get("line") else ""
        lines.append(f"## [{SEV_LABEL.get(f.severity, f.severity)}] {f.title}")
        lines.append("")
        lines.append(f"- **ID:** {f.id}")
        lines.append(f"- **Category:** {f.category} ({f.owasp})")
        lines.append(f"- **Confidence:** {f.confidence:.2f}")
        lines.append(f"- **Engine:** {f.engine}")
        if loc:
            lines.append(f"- **Location:** `{loc}`{line}")
        if f.evidence:
            ev = f.evidence.replace("\n", " ")[:300]
            lines.append(f"- **Evidence:** `{ev}`")
        if f.description:
            lines.append(f"- **Why it matters:** {f.description}")
        if f.remediation:
            lines.append(f"- **Fix:** {f.remediation}")
        if f.tags:
            lines.append(f"- **Tags:** {', '.join(f.tags)}")
        if f.mitre:
            lines.append(f"- **MITRE ATT&CK:** {', '.join(f.mitre)}")
        if f.references:
            lines.append("- **References:** " + ", ".join(f.references))
        lines.append("")

    lines.append("---")
    lines.append("*Generated by GRIM. Findings include confidence scores; verify before acting.*")
    return "\n".join(lines)


def render_summary_line(findings: Iterable[Finding]) -> str:
    s = summarize(findings)
    by = s["by_severity"]
    return (
        f"{s['total']} findings | critical:{by.get('critical',0)} high:{by.get('high',0)} "
        f"medium:{by.get('medium',0)} low:{by.get('low',0)} info:{by.get('info',0)}"
    )


def _version() -> str:
    from .. import __version__

    return __version__
